#!/usr/bin/env python
import os
import argparse
from helpers.compare_convergence import compare_convergence


def handle_args():
    parser = argparse.ArgumentParser(
        description="Compares the convergence of multiple results on a single dataset"
    )
    parser.add_argument(
        "--dataset_file",
        "-d",
        help="Path to the jrl dataset file",
        required=True,
    )
    parser.add_argument(
        "--constant_method_result_dirs",
        "-c",
        type=str,
        nargs="+",
        default=[]
    )
    parser.add_argument(
        "--method_result_dirs",
        "-m",
        type=str,
        nargs="+",
        help="Directories of method results.",
        default=[]
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = handle_args()
    compare_convergence(**vars(args))
