#!/usr/bin/env python
import os
import argparse
from helpers.compare_accuracy_to_comms import compare_accuracy_to_comms


def handle_args():
    parser = argparse.ArgumentParser(
        description="Compares the convergence of multiple results on a single dataset"
    )
    parser.add_argument(
        "--experiment_name",
        "-n",
        help="The name of the experiment",
        required=True,
    )
    parser.add_argument(
        "--dataset_dir",
        "-d",
        type=str,
        help="The dataset containing all the datasets for all trials",
        required=True,
    )
    parser.add_argument(
        "--result_dir",
        "-r",
        type=str,
        help="The directory containing all method results",
        required=True,
    )

    parser.add_argument(
        "--independent_variables",
        "-iv",
        type=str,
        nargs="+",
        help="The independent variables explored in the experiment",
        required=True,
    )
    parser.add_argument(
        "--all_methods",
        "-m",
        type=str,
        nargs="+",
        help="The names of all methods",
        required=True,
    )
    parser.add_argument(
        "--constant_methods",
        "-c",
        type=str,
        nargs="+",
        help="The names of constant_methods methods",
        required=True,
    )
    parser.add_argument(
        "--thresh",
        "-t",
        type=float,
        help="The threshold to compute final metrics",
        required=True,
    )
    parser.add_argument(
        "--legend",
        "-l",
         action="store_true",
        help="Plot the legend with the figure",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        help="The output destination for the figure",
        default=None
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = handle_args()
    compare_accuracy_to_comms(**vars(args))
